Accounts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.Home, name='home'),
    # url(r'^login/$', views.LoginView.as_view(template_name= 'login.html'), name='login'),
    # url(r'^logout/$', views.Logout, name='logout'),

    url(r'^login/$', views.Login, name='login'),
    url(r'^logout/$', views.Logout, name='logout'),
]

Profiles/urls.py
from django.conf.urls import url

from . import views

app_name = 'profiles'
urlpatterns = [
    url(r'^$', views.Home, name='home'),
    url(r'^(?P<slug>[-_@\w\.]+)/$', views.OpenProfile, name='profile')
]

ProjectsLogs/urls.py
from django.conf.urls import url
from . import views

app_name = 'projects'
urlpatterns = [
    url(r'^$', views.Home, name='home'),
    url(r'^adminstration/$', views.Adminstration, name='adminstration'),
    url(r'^adminstration/(?P<profile_slug>[-_@\w\.]+)/add-project/$', views.AddProject, name='add_project'),
    url(r'^adminstration/(?P<project_slug>[-_@\w\.]+)/edit-project/$', views.EditProject, name='edit_project'),


    url(r'^(?P<slug>[-_@\w\.]+)/$', views.OpenProject, name='project'),
    url(r'^replay/(?P<comment_id>\d+)/$', views.SubmitCommentReplay, name='submit_comment_replay'),
    url(r'^comment/(?P<change_type>[-_@\w\.]+)/(?P<change_id>\d+)/$', views.SubmitComment, name='submit_comment'),




]

ProjectsLogs/models.py
from django.db import models
from django.utils.text import slugify
import datetime
# Create your models here.
class Comment(models.Model):
    content = models.TextField()
    replay  = models.TextField(blank=True, null=True)
    seen    = models.BooleanField(default=False)

    comment_created = models.DateTimeField(editable=False, default=datetime.datetime.now)
    replay_created  = models.DateTimeField(null=True, blank=True)


    def save(self, *args, **kwargs):
        if self.replay:
            if not self.seen:
                self.replay_created = datetime.datetime.now()
            self.seen = True

        return super(Comment, self).save(*args, **kwargs)

    def __str__(self):
        return self.content[:15]+'...'

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

class Change(models.Model):
    ## change main data
    name    = models.CharField(max_length=70)
    explain = models.TextField()
    kind = models.CharField(editable=False, max_length=10, blank=True, null=True)


    ## data accroding to user
    accepted = models.BooleanField(default=True)
    user_notes  = models.ManyToManyField(Comment, blank=True)
    
    def __str__(self):
        return self.explain

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Change'
        verbose_name_plural = 'Changes'

class Added(Change):
    def save(self, *args, **kwargs):
        self.kind = 'added'
        return super(Added, self).save(*args, **kwargs)

class Removed(Change):
    def save(self, *args, **kwargs):
        self.kind = 'removed'
        return super(Removed, self).save(*args, **kwargs)

class Changed(Change):
    def save(self, *args, **kwargs):
        self.kind = 'changed'
        return super(Changed, self).save(*args, **kwargs)

class Deprecated(Change):
    def save(self, *args, **kwargs):
        self.kind = 'deprecated'
        return super(Deprecated, self).save(*args, **kwargs)

class Fixed(Change):
    def save(self, *args, **kwargs):
        self.kind = 'fixed'
        return super(Fixed, self).save(*args, **kwargs)

class Security(Change):
    def save(self, *args, **kwargs):
        self.kind = 'security'
        return super(Security, self).save(*args, **kwargs)

class Version(models.Model):
    ## version data
    version_number = models.CharField(max_length=15)
    critical_version = models.BooleanField()
    combitable_with_old_dependencies = models.BooleanField()

    created = models.DateTimeField(editable=False, default=datetime.datetime.now)

    ## version cide on github
    github_url      = models.URLField(null=True, blank=True, max_length=200)

    ## changes logs
    #project_changes = models.ManyToManyField(Change)
    added = models.ManyToManyField(Added, blank=True)
    removed = models.ManyToManyField(Removed, blank=True)
    changed = models.ManyToManyField(Changed, blank=True)
    deprecated = models.ManyToManyField(Deprecated, blank=True)
    fixed = models.ManyToManyField(Fixed, blank=True)
    security = models.ManyToManyField(Security, blank=True)

    def __str__(self):
        return self.version_number

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Version'
        verbose_name_plural = 'Versions'

class WebTechnology(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Coder(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Project(models.Model):
    project_name = models.CharField(max_length=70)
    slug         = models.SlugField(blank=True)
    project_versions = models.ManyToManyField(Version, blank=True)
    created      = models.DateTimeField(editable=False, default=datetime.datetime.now)

    ## data appear in profile table
    breif        = models.TextField(null=True, blank=True)
    coders       = models.ManyToManyField(Coder, blank=True)
    technologies = models.ManyToManyField(WebTechnology, blank=True)
    ## i work on it or update it
    under_work   = models.BooleanField(default=True)
    ## i work on it but you can try this beta version while am working
    can_try      = models.BooleanField(default=False)
    ## this project finished
    finished     = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.slug = slugify('%s' % self.project_name)
        return super(Project, self).save(*args, **kwargs)

    def __str__(self):
        return self.project_name

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Project'
        verbose_name_plural = 'Projects'

ProjectsLogs/forms.py
from django import forms
from .models import Comment, Project, Version, Change

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'content',
        )

class ReplayCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'replay',
        )

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = (
            'project_name',
            'breif',
            'coders',
            'technologies',
            'under_work',
            'can_try',
            'finished',
        )

class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = (
            'version_number',
            'critical_version',
            'combitable_with_old_dependencies',
            'github_url',
        )

class ChangeForm(forms.ModelForm):
    class Meta:
        model = Change
        fields = (
            'name', 
            'explain',
        )

ProjectsLogs/views.py
from django.http import HttpResponse
from functions import (
    # my functions
    is_logined,
    this_is_admin,
    get_object,
    redirect_prev_page,
    random_password,
    err_msg,
    Home,

    # builtin django
    reverse,
    redirect, 
    render,
)

from constants import (
    log_in,
    profile,
    change_types,
)

## models
from django.contrib.auth.models import User
from .models import Project, Version, Change, Comment
from Profiles.models import UserProfile

## forms
from .forms import CommentForm
from .forms import ProjectForm

## helpers
from json import loads

def has_access_to_project(request, project_slug):
    """ return project and context whitch tell he is admin or not"""
    if this_is_admin(request):
        context = {'admin': True}
        project = get_object(Project, slug=project_slug) ## get object or return None

    else:
        ## dont search in all projects just user's
        user_projects =  get_object(UserProfile, user=request.user)
        user_projects = user_projects.user_projects.all()
        has_access    = [project for project in user_projects if project.slug == project_slug]
        
        project = has_access.pop() if has_access else None
        context = {}

    return project, context

# Create your views here.
def OpenProject(request, slug):
    ## check he is_logined(request)
    if is_logined(request):
        ## be sure that user ask for his project or admin who ask
        project, context = has_access_to_project(request, slug)

        if project:
            versions= project.project_versions.all()
            comment_form = CommentForm()
            context.update({
                'project': project,
                'versions': versions,
                'comment_field': comment_form,
            })
            return render(request, 'project2.html', context)

        else:
            err_msg(request, 'You Dont Have Access For This Project')
            return redirect(profile)
    else:
        return redirect(log_in)

def SubmitComment(request, change_type, change_id):
    if is_logined(request):
        if request.method == 'POST':
            content = request.POST['content']

            ## add the comment to the table
            comment = Comment(content=content)
            comment.save()

            ## add the comment to the change
            Type = change_types[change_type]
            change = get_object(Type, id = change_id)
            change.user_notes.add(comment)

            return redirect_prev_page(request)
        else:
            return HttpResponse('this is not a post')
    else:
        return redirect(log_in)

def SubmitCommentReplay(request, comment_id):
    if is_logined(request):
        if request.method == 'POST':
            content = request.POST['content']

            ## add the comment to the table
            comment = get_object(Comment, id=comment_id)
            if comment and not comment.replay:
                clone_comment = comment
                clone_comment.replay = content
                
                comment = clone_comment
                comment.save()

            return redirect_prev_page(request)
        else:
            return HttpResponse('this is not a post')
    else:
        return redirect(log_in)


def Adminstration(request):
    if this_is_admin(request):
        context = {}

        if request.method == 'POST':
            ## this is create user from
            if request.POST.get('username'):
                ## get the field
                username = request.POST.get('username')
                ## check if exist already
                user = get_object(User, username=username)
                if not user:
                    password = random_password()
                    user     = User()
                    user.username = username
                    user.set_password(password)
                    user.save()

                    userProfile = get_object(UserProfile, user=user)
                    userProfile.p = password
                    userProfile.save()
                
                    context.update({'password': password})
                else:
                    err_msg(request, 'user already exist')

            ## this is search from
            if request.POST.get('search'):
                query = request.POST.get('search')
                search_type = request.POST.get('search-type')
                if search_type == 'user':
                    search_response = UserProfile.objects.filter(user__username__startswith=query)
                elif search_type == 'project':
                    search_response = Project.objects.filter(project_name__startswith=query)

                context.update({
                    'search_type': search_type,
                    'search_response': search_response,
                })

        ## - => to reverse the order
        profiles = UserProfile.objects.order_by('-user')
        projects = Project.objects.order_by('-created')
        context.update({
            'profiles': profiles,
            'projects': projects,
        })

        return render(request, 'adminstration.html', context)
    else:
        return redirect(profile)

def AddProject(request, profile_slug):
    if this_is_admin(request):
        if request.method == 'POST':
            ## save data
            ## get profile from user then save it
            profile = get_object(UserProfile, slug=profile_slug)
            if profile:
                ## create project
                add_project_form = ProjectForm(request.POST)
                if add_project_form.is_valid():
                    project = add_project_form.save()

                    ## add project to profile
                    profile.user_projects.add(project)
                
                    ## redirect to profile
                    user_link = reverse('profiles:profile', kwargs={'slug': profile_slug})
                    return redirect(user_link)

                else:
                    return redirect_prev_page(request)
            else:
                return HttpResponse('profile not found')

        elif request.method == 'GET':
            add_project_form = ProjectForm
            context = {
                'add_project_form': add_project_form,
            }
            return render(request, 'add-project.html', context)

## static function cuz its spesific case
def connect_change_and_version(version, change):
    """ this function to connet version  with its changes in its ManyToMany Fields """
    kind = change.kind
    
    if kind == 'added':
        version.added.add(change)
    elif kind == 'removed':
        version.removed.add(change)
    elif kind == 'changed':
        version.changed.add(change)
    elif kind == 'deprecated':
        version.deprecated.add(change)
    elif kind == 'fixed':
        version.fixed.add(change)
    elif kind == 'security':
        version.security.add(change)

def disconnect_change_and_version(version, change):
    """ this function to connet version  with its changes in its ManyToMany Fields """
    kind = change.kind
    
    if kind == 'added':
        version.added.remove(change)
    elif kind == 'removed':
        version.removed.remove(change)
    elif kind == 'changed':
        version.changed.remove(change)
    elif kind == 'deprecated':
        version.deprecated.remove(change)
    elif kind == 'fixed':
        version.fixed.remove(change)
    elif kind == 'security':
        version.security.remove(change)

def create_elm_in_table(Class, **kwargs):
    elm = Class(**kwargs)
    elm.save()

    return elm

def EditProject(request, project_slug):
    if this_is_admin(request):
        if request.method == 'POST':
            data = loads(request.POST['data'])
            
            ## change Original data of project
            project_org_data     = data['project_data']
            project              = get_object(Project, slug=project_slug)
            if project:
                project.project_name = project_org_data['project_name']
                project.breif        = project_org_data['brief']
                project.under_work   = project_org_data['worked_on']
                project.can_try      = project_org_data['can_try']
                project.finished     = project_org_data['finished']

                project.save()
                
                ## if i create new version
                if data['new_version']:
                    version_data = data['new_version']
                    version = create_elm_in_table(
                        Version,
                        version_number = version_data['version_number'],
                        critical_version = version_data['cretical'],
                        combitable_with_old_dependencies = version_data['combitable'],
                    )
                    project.project_versions.add(version)

                    version_changes = version_data['changes']
                    for change_type, values in version_changes.items():
                        Class = change_types[change_type]
                        for val in values:
                            change = create_elm_in_table(Class, explain= val)
                            connect_change_and_version(version, change)
                    
                ## if i edited an old version
                if data['old_version']:
                    version_data      = data['old_version']
                    editted_meta_data = version_data['editted_meta_data']
                    editted_changes   = version_data['editted_changes']
                    added_changes     = version_data['added_changes']

                    ## editted_meta_data : is dict of version id to its changes
                    for version_id, values in editted_meta_data.items():
                        version = get_object(Version, id=version_id)
                        if version:

ProjectsLogs/templates/add-project.html
<!-- files used in whole projects -->
{% include "base.html" %}

<style>

    #create-project{}
    #create-project form{
        width: 100%
    }

    #create-project input[type="text"],
    #create-project textarea{
        width: 100%;
        padding: 6px 12px;
    }

    #create-project textarea{
        height: 5em;
    }

    #create-project form > div{
        margin-bottom: 2em;
    }

    #create-project form > div:nth-of-type(3),
    #create-project form > div:nth-of-type(4){
        display: inline-block;
        width: 45%;
    }
    #create-project form > div:nth-of-type(4)::after{
        content: "";
        display: block;
        width: 100%;
    }

    #create-project form > div:nth-last-of-type(1),
    #create-project form > div:nth-last-of-type(2),
    #create-project form > div:nth-last-of-type(3){
        display: inline-block;
        border-left: 2px solid #333;
        padding-left: 10px;
        width: 30%;
    }

    #create-project input[type="submit"]{
        display: block;
        width: 100%;
    }

</style>
<div id="create-project" class="container">
    <div class="row center-text">
        <h3>Create Project.</h3>
    </div>
    <div class="row">
        <form method="POST">
            {% csrf_token %}
            
            
            {% for field in add_project_form %}
                <div>
                    <div>
                        {{field.label}}
                    </div>
                    {{field}}
                </div>
            {% endfor %}

            <input class="btn" type="submit" value="Add">
        </form>
    </div>
</div>

ProjectsLogs/templates/adminstration.html
<!-- files used in whole projects -->
{% extends "base.html" %}


{% block style %}    
<style>
    #adminstration-pg > .users{
        float: left;
        width: 50%;
    }

    #adminstration-pg > .projects{
        float: right;
        width: 50%;
    }

    #adminstration-pg::after{
        content: "";
        display: block;
        width: 100%;
        clear: both;
    }

    #create-user, 
    #search {
        width: 40%;
        min-width: 300px;
        max-width: 400px;
        padding: 20px;
        margin: auto;
        padding: 15px;

        display: inline-block;
    }

    @media (max-width: 800px){
        #create-user, 
        #search {
            display: block !important;
        }
    }

    #create-user input,
    #search input, #search select{
        border: none;
        display: block;
        width: 100%;
        max-width: 200px;
        min-width: 100px;
        margin: auto;
        text-align: center;
        font-size: 0.8em;
        padding: 6px 12px;
        margin-bottom: 10px;
        border-radius: 5px;
    }

    #create-user input[type="text"], 
    #search input[type="search"]{
        box-shadow: 0px 2px 5px -2px #CCC;
    }

    #create-user input[type="submit"],
    #search input[type="submit"]{
        background-color: #173ff5;
        color: #FFF;
        font-weight: bolder;
        letter-spacing: 5px;
        border-radius: 20px;
        cursor: pointer;

    }

    #search div{
        display: flex;
    }

    #search div input{
        width: 100%;
        max-width: none;
    }
    #search div select{
        width: 86px;
        min-width: 86px;
        max-width: 86px;

        cursor: pointer;
    }

    input{
        outline: 0;
    }

</style>
{% endblock style %}
    

{% block content %}    
<div id="adminstration-pg" class="container">
    <div id="create-user">
        <form method="post">
            {% csrf_token %}
            <input autocomplete="off" type="text" name="username" placeholder="UserName">
            <input type="submit" value="Add-User">
        </form>
        <!-- <div id="password">{{password}}</div> -->
    </div>

    <div id="search">
        <form method="post">
            {% csrf_token %}
            <div>
                <input autocomplete="off" type="search" name="search" placeholder="Search">
                <select name="search-type">
                    <option value="project">Project</option>
                    <option value="user">User</option>
                </select>
            </div>
            <input type="submit" value="search">
        </form>
    </div>

    <div id="search-output">
        
        {% if search_type == 'project' %}   
            <h3>Search Result: Projects</h3>
            {% for project in search_response %}
                <a href="{% url 'projects:project' project.slug %}">
                    {{project.project_name}}
                </a>
                <br>
            {% endfor %}
        {% elif search_type == 'user' %}
            <h3>Search Result: Users</h3>
            {% for profile in search_response %}
                <a href="{% url 'profiles:profile' profile.slug %}">
                    {{profile.user.username}} 
                </a>
                <br>
            {% endfor %}
        {% endif %}

        <br> <br>
    </div>

    <div class="users">
        <h3>All Users</h3>
        {% for profile in profiles %}
            <a href="{% url 'profiles:profile' profile.slug %}">
                {{profile.user.username}}
            </a>:
            <span>{{ profile.p }}</span>
            <br>
        {% endfor %}
    </div>
        
    <div class="projects">
        <h3>All Projects</h3>
        {% for project in projects %}
            <a href="{% url 'projects:project' project.slug %}">
                {{project.project_name}}
            </a>
            <br>
        {% endfor %}
    </div>
</div>
{% endblock content %}

ProjectsLogs/templates/changes.html
<!-- this file just to dont repeat myself -->

<ul>
    <li>
        {{change.name}}: {{change.explain}}
        {% if change.accepted %}
            <span style="color:green;">(accepted)</span>
        {% else %}
            <span style="color:red;">(refused)</span>
        {% endif %}

        <br>

        <div style="padding-top: 30px ">
        {% with change.user_notes.all as comments %}
        {% for comment in comments %}
            content: {{comment.content}} <br>
            content_created: {{comment.comment_created}} <br> <br>
            replay: {{comment.replay}}<br>
            replay_created: {{comment.replay_created}} <br>
            seen: {{comment.seen}}<br>
        {% endfor %}
        <form action="{% url 'projects:submit_comment' change.kind change.pk %}" method="POST">
            {% csrf_token %}
            <textarea name="{{comment_field.content.name}}" cols="40" rows="2"></textarea>
            <input type="submit" value="comment">
        </form>
        {% endwith %}
        </div>
    </li>
</ul>

ProjectsLogs/templates/changes2.html
<li>
    <span></span>
    {{change.name}} {{change.explain|safe}}
</li>

<!-- change comments -->
<div class="comments" style="display:none;">

    {% with change.user_notes.all as comments %}
    {% for comment in comments %}
    <div class="comment">
        <div class="content">
            {{comment.content}}
        </div>
        <div class="created">
            {{comment.comment_created}}
        </div>
        
        {% if comment.replay %}
        <div class="replay">
            <div class="content">
                {{comment.replay}}
            </div>
            <div class="created">
                {{comment.replay_created}}
            </div>
        </div>
        {% else %}
            {% if admin %}
            <form action="{% url 'projects:submit_comment_replay' comment.id %}" method="POST">
                {% csrf_token %}
                <textarea name="content"></textarea>
                <input class="btn" type="submit" value="Submit Replay">
            </form>
            {% endif %}
        {% endif %}
    </div>
    {% endfor %}
    
    {% if not admin %}    
    <form action="{% url 'projects:submit_comment' change.kind change.pk %}" method="POST">
        {% csrf_token %}
        <textarea name="content"></textarea>
        <input class="btn" type="submit" value="Submit Comment">
    </form>
    {% endif %}
        
    {% endwith %}

</div>

ProjectsLogs/templates/create-project.html
<!-- files used in whole projects -->
{% include "base.html" %}

<form method="post">
    {% csrf_token %}
    {{form1}}
    <br> <br>
    {{form2}}
    <input type="submit" value="submits">
</form>

<!--
{{form2.username.help_text}}
-->

ProjectsLogs/templates/project.html
{% extends "base.html" %}


{% block content %}   
{% if admin %}
    <a href="{% url 'projects:edit_project' project.slug %}">edit project</a>
{% endif %}
    

<h1>
    {{project.project_name}}
    <span style="font-size: .5em">
        {{project.created}}
    </span>
</h1>

{% with project.project_versions.all as versions %}
{% for version in versions %}
    <h3>
        <a href="{{version.github_url | default_if_none:'#'}}">
            {{version.version_number}}
        </a>
        <span style="font-size:.65em;">
            {{version.created}}
            {% if version.critical_version %}
                <span style="color:red;">(critical)</span>
            {% endif %}
            
            {% if not version.combitable_with_old_dependencies %}
                <span style="color:red;">(not compitable)</span>
            {% endif %}
        </span>
    </h3>
    
    {% with version.added.all as added %}
        {% if added %}
            <h3>Added</h3>
            {% for change in added %}
                {% include "changes.html" %}
            {% endfor %}
        {% endif %}
    {% endwith %}

    {% with version.removed.all as removed %}
        {% if removed %}
            <h3>Removed</h3>
            {% for change in removed %}
                {% include "changes.html" %}
            {% endfor %}
        {% endif %}
    {% endwith %}

    {% with version.changed.all as changed %}
        {% if changed %}
            <h3>Changed</h3>
            {% for change in changed %}
                {% include "changes.html" %}
            {% endfor %}
        {% endif %}
    {% endwith %}

    {% with version.deprecated.all as deprecated %}
        {% if deprecated %}
            <h3>Deprecated</h3>
            {% for change in deprecated %}
                {% include "changes.html" %}
            {% endfor %}
        {% endif %}
    {% endwith %}

    {% with version.fixed.all as fixed %}
        {% if fixed %}
            <h3>Fixed</h3>
            {% for change in fixed %}
                {% include "changes.html" %}
            {% endfor %}
        {% endif %}
    {% endwith %}

    {% with version.security.all as security %}
        {% if security %}
            <h3>Security</h3>
            {% for change in security %}
                {% include "changes.html" %}
            {% endfor %}
        {% endif %}
    {% endwith %}




    
{% endfor %}
{% endwith %}

{% endblock content %}