Accounts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.Home, name='home'),
    # url(r'^login/$', views.LoginView.as_view(template_name= 'login.html'), name='login'),
    # url(r'^logout/$', views.Logout, name='logout'),

    url(r'^login/$', views.Login, name='login'),
    url(r'^logout/$', views.Logout, name='logout'),
]

Profiles/urls.py
from django.conf.urls import url

from . import views

app_name = 'profiles'
urlpatterns = [
    url(r'^$', views.Home, name='home'),
    url(r'^(?P<slug>[-_@\w\.]+)/$', views.OpenProfile, name='profile')
]

ProjectsLogs/urls.py
from django.conf.urls import url
from . import views

app_name = 'projects'
urlpatterns = [
    url(r'^$', views.Home, name='home'),
    url(r'^adminstration/$', views.Adminstration, name='adminstration'),
    url(r'^adminstration/(?P<profile_slug>[-_@\w\.]+)/add-project/$', views.AddProject, name='add_project'),
    url(r'^adminstration/(?P<project_slug>[-_@\w\.]+)/edit-project/$', views.EditProject, name='edit_project'),


    url(r'^(?P<slug>[-_@\w\.]+)/$', views.OpenProject, name='project'),
    url(r'^replay/(?P<comment_id>\d+)/$', views.SubmitCommentReplay, name='submit_comment_replay'),
    url(r'^comment/(?P<change_type>[-_@\w\.]+)/(?P<change_id>\d+)/$', views.SubmitComment, name='submit_comment'),




]

Profiles/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class UserProfile(models.Model):
    ## fields
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True)
    user_projects = models.ManyToManyField("ProjectsLogs.Project", blank=True)
    p = models.CharField(max_length=100, blank=True, null= True)

    def save(self, *args, **kwargs):
        self.slug = slugify('%s' % self.user)
        return super(UserProfile, self).save(*args, **kwargs)

    def __str__(self):
        return '%s' % self.user

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'UserProfile'
        verbose_name_plural = 'UserProfiles'

def create_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user= instance)

post_save.connect(create_profile, sender=User)

Profiles/views.py
# Create your views here.
from django.http import HttpResponse
from .models import UserProfile
from functions import (
    # my functions
    get_object,
    this_is_admin, 
    is_logined,
    Home,
    # builtin django
    render,
    redirect,
    slugify,
)

from constants import (
    log_in,
    profile,
)

# Create your views here.

## helper function not main view function
def load_profile(request, slug, context={}):
    """ to load user profile throw the slug """
    profile = get_object(UserProfile,slug=slug)
    if profile:
        context.update({
            'profile' : profile,
            'user'    : profile.user, ## forignkey
            'projects': profile.user_projects.all(), ## ManyToMany
        })
        return render(request, 'profile.html', context)

    else:
        return HttpResponse('there is no profile for this user<br> contact with us')

def OpenProfile(request, slug):
    """ user can only open his profile """

    ## first check he is logined
    if is_logined(request):

        ## check if he ask for his profile 
        # else see if he admin else redirect to his profile
        user    = request.user.username
        if slug == slugify(user):
            ## load his profile
            return load_profile(request, slug)
        else:
            if this_is_admin(request):
                ## load profile as admin give u access to create projects
                context = {'admin': True}
                return load_profile(request, slug, context)
                
            else:
                ## someone try to access other redirect him to his profile
                return redirect(profile)
    else:
        ## not logined has no access to any profile
        return redirect(log_in)

Profiles/templates/profile.html
<!-- files used in whole projects -->
{% include "base.html" %}

<div id="profile">
    {% if admin %}
        <header>
            <h3>{{user.username}}</h3> 
            <a class="btn" href="{% url 'projects:add_project' profile.slug %}">Add Project</a> <br>
        </header>
    {% else %}
        <header>
            <h3>Welcome {{user.username}}</h3> 
            <!-- <a href="{% url 'accounts:logout' %}">logout</a> -->
        </header>
    {% endif %}

    {% if projects %}
    <div id="projects">
        <h4>Projects</h4>

        <div class="divTable">
            <!-- Table header -->
            <div class="divTableHeading">
                <div class="divTableHead">Name</div>
                <div class="divTableHead">Created</div>
                <div class="divTableHead">Brief</div>
                <div class="divTableHead">Coders</div>
                <div class="divTableHead">Tech/s</div>
                <div class="divTableHead">Versions</div>
            </div>
            <div class="divTableBody">


                {% for project in projects %}
                <div class="divTableRow {% cycle 'row1' 'row2' %}">
                    <div class="divTableCell name">
                        <a href="{% url 'projects:project' project.slug %}">
                            {{project.project_name}}
                        </a>
                    </div>
                    
                    <div class="divTableCell created">
                        {{project.created}}
                    </div>

                    <div class="divTableCell brief">
                        {{project.breif}}
                    </div>
                    
                    <div class="divTableCell coders">
                        {% for coder in project.coders.all %}
                            <div>{{coder}}</div>
                        {% endfor %}
                    </div>
                    
                    <div class="divTableCell technologies">
                        {% for tech in project.technologies.all %}
                            <div>{{tech}}</div>
                        {% endfor %}
                    </div>
                    
                    <div class="divTableCell version-count">
                        {{project.project_versions.count}}
                    </div>
                </div>                
                {% endfor %}
                
            </div>
        </div>
        <!-- DivTable.com -->
    </div>
    {% else %}
    <p style="text-align: center; background-color: #EEE; padding: 12px; border-radius: 15px;">There is no projects yet</p>
    {% endif %} 

</div>    